[2023-05-04T10:44:54.884+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.third_task scheduled__2021-11-23T00:00:00+00:00 [queued]>
[2023-05-04T10:44:54.949+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.third_task scheduled__2021-11-23T00:00:00+00:00 [queued]>
[2023-05-04T10:44:54.952+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-05-04T10:44:55.453+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): third_task> on 2021-11-23 00:00:00+00:00
[2023-05-04T10:44:55.533+0000] {standard_task_runner.py:57} INFO - Started process 3604 to run task
[2023-05-04T10:44:55.579+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'third_task', 'scheduled__2021-11-23T00:00:00+00:00', '--job-id', '981', '--raw', '--subdir', 'DAGS_FOLDER/our_fist_dag.py', '--cfg-path', '/tmp/tmp7r5ygekb']
[2023-05-04T10:44:55.721+0000] {standard_task_runner.py:85} INFO - Job 981: Subtask third_task
[2023-05-04T10:44:56.264+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag_v3.third_task scheduled__2021-11-23T00:00:00+00:00 [running]> on host a2c266875370
[2023-05-04T10:44:56.636+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose-holgado' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2021-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-11-23T00:00:00+00:00'
[2023-05-04T10:44:56.640+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-04T10:44:56.642+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 and with same time as task 2']
[2023-05-04T10:44:56.776+0000] {subprocess.py:86} INFO - Output:
[2023-05-04T10:44:56.782+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task1 and with same time as task 2
[2023-05-04T10:44:56.791+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-05-04T10:44:57.051+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, execution_date=20211123T000000, start_date=20230504T104454, end_date=20230504T104457
[2023-05-04T10:44:57.335+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-04T10:44:57.805+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
